In [1]:
v = [3, 2]
print(v)

[3, 2]


In [2]:
import numpy as np

v = np.array([3, 2])
print(v)

[3 2]


In [1]:
import numpy as np

v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [2]:
import numpy as np

v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


In [3]:
from numpy import array

v = array([3, 2])
w = array([2, -1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


In [4]:
from numpy import array

v = array([3, 1])
scaled_v = 2.0 * v
print(scaled_v)

[6. 2.]


In [5]:
from numpy import array

basis = array(
    [[3, 0],
     [0, 2]]
)
v = array([1, 1])
new_v = basis.dot(v)
print(new_v)

[3 2]


In [6]:
from numpy import array

i_hat = array([2, 0])
j_hat = array([0, 3])
basis = array([i_hat, j_hat]).transpose()
v = array([1, 1])
new_v = basis.dot(v)
print(new_v)

[2 3]


In [7]:
from numpy import array

i_hat = array([2, 0])
j_hat = array([0, 3])
basis = array([i_hat, j_hat]).transpose()
v = array([2, 1])
new_v = basis.dot(v)
print(new_v)

[4 3]


In [8]:
from numpy import array

i_hat = array([2, 3])
j_hat = array([2, -1])
basis = array([i_hat, j_hat]).transpose()
v = array([2, 1])
new_v = basis.dot(v)
print(new_v)

[6 5]


In [9]:
from numpy import array

i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
combined = transform2 @ transform1
print("통합 행렬:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v))

통합 행렬:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [10]:
from numpy import array

i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
combined = transform1 @ transform2
print("통합 행렬:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v))

통합 행렬:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


In [11]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

6.0


In [12]:
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

1.0


In [13]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

-5.000000000000001


In [14]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, -1.5])
j_hat = array([-2, 1])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

0.0


In [15]:
from sympy import *

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
inverse = A.inv()
identity = inverse * A
print("역행렬: {}".format(inverse))
print("항등 행렬: {}".format(identity))

역행렬: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
항등 행렬: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [16]:
from numpy import array
from numpy.linalg import inv

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
B = array([
    44,
    56,
    72
])
X = inv(A).dot(B)
print(X)

[ 2. 34. -8.]


In [17]:
from sympy import *

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
B = Matrix([
    44,
    56,
    72
])
X = A.inv() * B
print(X)

Matrix([[2], [34], [-8]])


In [18]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])
eigenvals, eigenvecs = eig(A)
print("고윳값")
print(eigenvals)
print("\n고유 벡터")
print(eigenvecs)

고윳값
[-0.46410162  6.46410162]

고유 벡터
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [19]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])
eigenvals, eigenvecs = eig(A)
print("고윳값")
print(eigenvals)
print("\n고유 벡터")
print(eigenvecs)
print("\n재구성 행렬")
Q = eigenvecs
R = inv(Q)
L = diag(eigenvals)
B = Q @ L @ R
print(B)

고윳값
[-0.46410162  6.46410162]

고유 벡터
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

재구성 행렬
[[1. 2.]
 [4. 5.]]


In [20]:
from numpy import array

v = array([1, 2])
i_hat = array([2, 0])
j_hat = array([0, 1.5])
basis = array([i_hat, j_hat])
w = basis.dot(v)
print(w)

[2. 3.]


In [21]:
from numpy import array

v = array([1, 2])
i_hat = array([-2, 1])
j_hat = array([1, -2])
basis = array([i_hat, j_hat])
w = basis.dot(v)
print(w)

[ 0 -3]


In [22]:
import numpy as np

a = np.array([[3, -2], [1, 4]])
b = np.array([[5, 2], [3, -1]])
c = a.dot(b)
print(c)

[[ 9  8]
 [17 -2]]


In [23]:
import numpy as np
from numpy.linalg import det

i_hat = np.array([1, 0])
j_hat = np.array([2, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

2.0


In [24]:
import numpy as np

A = np.array([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ 0.3875 -0.1     0.0125]
 [-0.1625  0.3    -0.0375]
 [-0.125   0.      0.125 ]]


In [25]:
from numpy import array
from numpy.linalg import inv

A = array([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])
B = array([
    54,
    12,
    6
])
X = inv(A).dot(B)
print(X)

[19.8 -5.4 -6. ]


In [26]:
from numpy.linalg import det
from numpy import array

i_hat = array([2, 6])
j_hat = array([1, 3])
basis = array([i_hat, j_hat]).transpose()
print(basis)
determinant = det(basis)
print(determinant)

[[2 1]
 [6 3]]
-3.330669073875464e-16


In [27]:
import numpy as np

A = np.array([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])
eigenvals, eigenvecs = np.linalg.eig(A)
print("고윳값\n", eigenvals)
print("고유벡터\n", eigenvecs)
A_reconstruction = eigenvecs @ np.diag(eigenvals) @ np.linalg.inv(eigenvecs)
print("재구성 행렬\n", np.round(A_reconstruction))

고윳값
 [8.38761906 2.12592447 4.48645647]
고유벡터
 [[-0.04479915 -0.72643433 -0.45454378]
 [-0.24136078  0.63495848 -0.67565954]
 [-0.96940085  0.26290852  0.5804086 ]]
재구성 행렬
 [[3. 1. 0.]
 [2. 4. 1.]
 [3. 1. 8.]]
